name: QA Table Scraping

on: [push]

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    name: Run QA Script - 22f3000980@ds.study.iitm.ac.in
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install

      - name: Run Scraping Script
        run: python scrape_tables.py
